# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bd0a15ad24267c493677dcd2ebbb2b02b161f3232cc6ab0f9e8ad855dd8f2457e86d9350425c94311d2aae812699e163cb3ea9f59940fca5692fad2e3d53a7a

test:
  secret_key_base: 47694976ce5f18a69d816b481d1f1d65cc84531c12e7b1a7cbd6f7ebf4acbe5111d04621ae853aed5a818ac81509d49ac20e5dbe72a4d73b1de0a371367aeabd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
